// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: rpc/orchestrator.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Arg1          float64                `protobuf:"fixed64,2,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2          float64                `protobuf:"fixed64,3,opt,name=arg2,proto3" json:"arg2,omitempty"`
	Operation     string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	OperationTime uint32                 `protobuf:"varint,5,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMessage) Reset() {
	*x = TaskMessage{}
	mi := &file_rpc_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMessage) ProtoMessage() {}

func (x *TaskMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMessage.ProtoReflect.Descriptor instead.
func (*TaskMessage) Descriptor() ([]byte, []int) {
	return file_rpc_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *TaskMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskMessage) GetArg1() float64 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *TaskMessage) GetArg2() float64 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *TaskMessage) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *TaskMessage) GetOperationTime() uint32 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result        float64                `protobuf:"fixed64,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_rpc_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_rpc_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResult) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskResult) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_rpc_orchestrator_proto protoreflect.FileDescriptor

const file_rpc_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x16rpc/orchestrator.proto\x12\forchestrator\x1a\x1bgoogle/protobuf/empty.proto\"\x8a\x01\n" +
	"\vTaskMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04arg1\x18\x02 \x01(\x01R\x04arg1\x12\x12\n" +
	"\x04arg2\x18\x03 \x01(\x01R\x04arg2\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x12%\n" +
	"\x0eoperation_time\x18\x05 \x01(\rR\roperationTime\"4\n" +
	"\n" +
	"TaskResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x01R\x06result2\x8c\x01\n" +
	"\fOrchestrator\x12<\n" +
	"\aGetTask\x12\x16.google.protobuf.Empty\x1a\x19.orchestrator.TaskMessage\x12>\n" +
	"\n" +
	"PostResult\x12\x18.orchestrator.TaskResult\x1a\x16.google.protobuf.EmptyBWZUgithub.com/VaDKustiK/yandex-golang-course/calculator_service/pkg/orchestrator/rpc;rpcb\x06proto3"

var (
	file_rpc_orchestrator_proto_rawDescOnce sync.Once
	file_rpc_orchestrator_proto_rawDescData []byte
)

func file_rpc_orchestrator_proto_rawDescGZIP() []byte {
	file_rpc_orchestrator_proto_rawDescOnce.Do(func() {
		file_rpc_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_orchestrator_proto_rawDesc), len(file_rpc_orchestrator_proto_rawDesc)))
	})
	return file_rpc_orchestrator_proto_rawDescData
}

var file_rpc_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_orchestrator_proto_goTypes = []any{
	(*TaskMessage)(nil),   // 0: orchestrator.TaskMessage
	(*TaskResult)(nil),    // 1: orchestrator.TaskResult
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_rpc_orchestrator_proto_depIdxs = []int32{
	2, // 0: orchestrator.Orchestrator.GetTask:input_type -> google.protobuf.Empty
	1, // 1: orchestrator.Orchestrator.PostResult:input_type -> orchestrator.TaskResult
	0, // 2: orchestrator.Orchestrator.GetTask:output_type -> orchestrator.TaskMessage
	2, // 3: orchestrator.Orchestrator.PostResult:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_orchestrator_proto_init() }
func file_rpc_orchestrator_proto_init() {
	if File_rpc_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_orchestrator_proto_rawDesc), len(file_rpc_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_orchestrator_proto_goTypes,
		DependencyIndexes: file_rpc_orchestrator_proto_depIdxs,
		MessageInfos:      file_rpc_orchestrator_proto_msgTypes,
	}.Build()
	File_rpc_orchestrator_proto = out.File
	file_rpc_orchestrator_proto_goTypes = nil
	file_rpc_orchestrator_proto_depIdxs = nil
}
